CREATE TABLE "user" (
  "id_user" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_rol" integer,
  "ced_user" varchar(20),
  "name" varchar(20),
  "lastname" varchar(20),
  "email" varchar(50),
  "password" varchar(500)
);

CREATE TABLE "role" (
  "id_role" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "rol_name" varchar(20),
  "rol_descrip" varchar(200)
);

CREATE TABLE "institution" (
  "id_inst" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "inst_name" varchar(50),
  "descrip_inst" varchar(140),
  "locate_id" integer
);

CREATE TABLE "user_institution" (
  "id_user" integer,
  "id_inst" integer
);

CREATE TABLE "parroquia" (
  "id_parr" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name_parr" varchar(50),
  "id_mun" integer
);

CREATE TABLE "municipio" (
  "id_mun" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name_mun" varchar(50),
  "id_est" integer
);

CREATE TABLE "estado" (
  "id_est" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name_est" varchar(50)
);

ALTER TABLE "municipio" ADD FOREIGN KEY ("id_est") REFERENCES "estado" ("id_est");

ALTER TABLE "parroquia" ADD FOREIGN KEY ("id_mun") REFERENCES "municipio" ("id_mun");

ALTER TABLE "institution" ADD FOREIGN KEY ("locate_id") REFERENCES "parroquia" ("id_parr");

ALTER TABLE "user_institution" ADD FOREIGN KEY ("id_user") REFERENCES "user" ("id_user");

ALTER TABLE "user_institution" ADD FOREIGN KEY ("id_inst") REFERENCES "institution" ("id_inst");

ALTER TABLE "user" ADD FOREIGN KEY ("id_rol") REFERENCES "role" ("id_role");


INSERT INTO "role" VALUES (default, 'Profesor', 'Este rol permite a los usuarios crear las actividades y ver el progreso de sus estudiantes')
INSERT INTO "role" VALUES (default, 'Estudiante', 'Este rol permite a los usuarios participar en las actividades y ver su progreso')