----- CREACIÓN DE LA BASE DE DATOS -------------------

CREATE TABLE "user" (
  "id_user" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ced_user" varchar(20) NOT NULL CHECK (TRIM(ced_user) <> ''),
  "name" varchar(20) NOT NULL CHECK (TRIM(name) <> ''),
  "lastname" varchar(20) NOT NULL CHECK (TRIM(lastname) <> ''),
  "email" varchar(50) NOT NULL UNIQUE CHECK (TRIM(email) <> ''),
  "password" varchar(20) NOT NULL CHECK (TRIM(password) <> '')
);


CREATE TABLE "institution" (
  "id_inst" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "inst_name" varchar(50) NOT NULL CHECK (TRIM(inst_name) <> ''),
  "descrip_inst" varchar(140),
  "locate_id" integer NOT NULL
);

CREATE TABLE "user_institution" (
  "id_user" integer NOT NULL,
  "id_inst" integer NOT NULL
);

CREATE TABLE "parroquia" (
  "id_parr" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name_parr" varchar(50) NOT NULL CHECK (TRIM(name_parr) <> ''),
  "id_mun" integer NOT NULL
);

CREATE TABLE "municipio" (
  "id_mun" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name_mun" varchar(50) NOT NULL CHECK (TRIM(name_mun) <> ''),
  "id_est" integer NOT NULL
);

CREATE TABLE "estado" (
  "id_est" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name_est" varchar(50) NOT NULL CHECK (TRIM(name_est) <> '')
);

ALTER TABLE "municipio" ADD FOREIGN KEY ("id_est") REFERENCES "estado" ("id_est");

ALTER TABLE "parroquia" ADD FOREIGN KEY ("id_mun") REFERENCES "municipio" ("id_mun");

ALTER TABLE "institution" ADD FOREIGN KEY ("locate_id") REFERENCES "parroquia" ("id_parr");

ALTER TABLE "user_institution" ADD FOREIGN KEY ("id_user") REFERENCES "user" ("id_user");

ALTER TABLE "user_institution" ADD FOREIGN KEY ("id_inst") REFERENCES "institution" ("id_inst");

------------ INSERTS -----------------

INSERT INTO "user" VALUES (default, '29758164', 'Luis', 'Chang', 'luischang16@hotmail.com', 'password');
INSERT INTO "user" VALUES (default, '11891376', 'Maribel', 'Piña', 'maribelpina@hotmail.com', 'password');